fun main() {
    val comments = Comments(21, true, false, true, true)
    val copyright = Copyright(52154, "id.com/52154", "Victor", "Superuser")
    val donut = Donut(true, 240, canPublishFreeCopy = false, editMode = "all")
    val likes = Likes(110, true, true, true)
    val reposts = Reposts(100, true)
    val views = Views(220)
    val wallService = WallService
    val post1 = Post(
        ownerId = 607,
        fromId = 61279,
        createdBy = 45,
        date = 130305,
        text = "Первый пост",
        replyOwnerID = 343,
        replyPostId = 435,
        friendsOnly = true,
        comments = comments,
        copyright = copyright,
        likes = likes,
        reposts = reposts,
        views = views,
        postType = "post",
        signerId = 2342,
        canPin = true,
        canDelete = true,
        canEdit = true,
        isPinned = false,
        markedAsAds = false,
        isFavorite = false,
        donut = donut,
        postponedId = 3563463
    )
    val post2 = Post(
        ownerId = 6887,
        fromId = 679,
        createdBy = 8977,
        date = 1303545,
        text = "Hello world",
        replyOwnerID = 343,
        replyPostId = 435,
        friendsOnly = true,
        comments = comments,
        copyright = copyright,
        likes = likes,
        reposts = reposts,
        views = views,
        postType = "post",
        signerId = 2342,
        canPin = true,
        canDelete = true,
        canEdit = true,
        isPinned = false,
        markedAsAds = false,
        isFavorite = false,
        donut = donut,
        postponedId = 3563463
    )
    val post3 = Post(
        id = 1,
        ownerId = 607,
        fromId = 3465,
        createdBy = 45634,
        date = 130324,
        text = "обновленный пост",
        replyOwnerID = 343,
        replyPostId = 435,
        friendsOnly = true,
        comments = comments,
        copyright = copyright,
        likes = likes,
        reposts = reposts,
        views = views,
        postType = "post",
        signerId = 2342,
        canPin = true,
        canDelete = true,
        canEdit = true,
        isPinned = false,
        markedAsAds = false,
        isFavorite = false,
        donut = donut,
        postponedId = 3563463
    )
}